name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_URL: "https://demo-eyes-actions-netlify.netlify.app"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Wait for Netlify Deploy
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: "deploy/netlify"
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        
    - if: ${{ github.event.pull_request }}
      name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.2
      id: demo
      with:
        site_name: "demo-eyes-actions-netlify"
    
    - if: ${{ github.event.pull_request }}
      name: Storing Preview URL in Environment
      run: echo "DEPLOY_URL=${{ steps.demo.outputs.url }}" >> $GITHUB_ENV

    - uses: colbyfayock/applitools-eyes-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        APPLITOOLS_BATCH_ID: ${{ github.sha }}
        appName: Demo Eyes Actions Netlify
        baseUrl: ${{ env.DEPLOY_URL }}
        depth: 2
