name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.2
      id: demo
      with:
        site_name: "demo-eyes-actions-netlify"

    - uses: colbyfayock/applitools-eyes-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        APPLITOOLS_BATCH_ID: ${{ github.sha }}
        appName: Demo Eyes Actions Netlify
        baseUrl: ${{ steps.demo.outputs.url }}
        depth: 2
