name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.2
      id: demo
      with:
        site_name: "demo-eyes-actions-netlify"

    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{ env.APPLITOOLS_API_KEY }}
        APPLITOOLS_BATCH_ID: ${{ env.APPLITOOLS_BATCH_ID }}
        appName: Demo Eyes Actions Netlify
        baseUrl: ${{ steps.demo.outputs.url }}

  batch-completion-notification:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ env.APPLITOOLS_API_KEY }}
